rhs9[i] = G0[i] * np.real(conv2(If[:, i], If[:, i], Vdc[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc)) + g_conv[i] * (conv1(M[:, i], Vdc_re[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_re[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) - b_conv[i] * (conv1(M[:, i], Vdc_im[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_im[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) - bc_shunt[i] / 2 * conv2(M[:, i], M[:, i], Vdc_im[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc) - g_conv[i] * (conv1(Vac_re[:, b_ac_c[i]], E_re[:, tr_E], 1, cc-1, 0, cc) + conv2(M[:, i], Vac_re[:, b_ac_c[i]], E_re[:, tr_E], 1, 0, cc-1, cc, 0, cc)) - g_conv[i] * (conv1(Vac_im[:, b_ac_c[i]], E_im[:, tr_E], 1, cc-1, 0, cc) + conv2(M[:, i], Vac_im[:, b_ac_c[i]], E_im[:, tr_E], 1, 0, cc-1, cc, 0, cc)) + b_conv[i] * (conv1(Vac_im[:, b_ac_c[i]], E_re[:, tr_E], 1, cc-1, 0, cc) + conv2(M[:, i], Vac_im[:, b_ac_c[i]], E_re[:, tr_E], 1, 0, cc-1, cc, 0, cc)) + np.real(1j * conv3(B[:, tr_B], M[:, i], M[:, i], Vdc[:, b_dc_c[i]], 0, 0, 0, cc-2, cc-1, cc-1, 1, cc)) - b_conv[i] * conv2(M[:, i], E_im[:, tr_E], Vac_re[:, b_ac_c[i]], 0, 0, cc-1, cc-1, 1, cc)

rhs9[i] = G0[i] * np.real(conv2(If[:, i], If[:, i], Vdc[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc)) + g_conv[i] * (conv1(M[:, i], Vdc_re[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_re[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) - b_conv[i] * (conv1(M[:, i], Vdc_im[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_im[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) - bc_shunt[i] / 2 * conv2(M[:, i], M[:, i], Vdc_im[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc) - g_conv[i] * conv1(M[:, i], Vac_re[:, b_ac_c[i]], 1, cc-1, 0, cc) + b_conv[i] * conv1(M[:, i], Vac_im[:, b_ac_c[i]], 1, cc-1, 0, cc) + np.real(1j * conv3(B[:, tr_B], M[:, i], M[:, i], Vdc[:, b_dc_c[i]], 0, 0, 0, cc-2, cc-1, cc-1, 1, cc))

rhs9[i] = G0[i] * np.real(conv2(If[:, i], If[:, i], Vdc[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc)) + g_conv[i] * (conv1(M[:, i], Vdc_re[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_re[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) - b_conv[i] * (conv1(M[:, i], Vdc_im[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_im[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) - bc_shunt[i] / 2 * conv2(M[:, i], M[:, i], Vdc_im[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc) - g_conv[i] * (conv1(Vac_re[:, b_ac_c[i]], E_re[:, tr_E], 1, cc-1, 0, cc) + conv2(M[:, i], Vac_re[:, b_ac_c[i]], E_re[:, tr_E], 1, 0, cc-1, cc, 0, cc)) - g_conv[i] * (conv1(Vac_im[:, b_ac_c[i]], E_im[:, tr_E], 1, cc-1, 0, cc) + conv2(M[:, i], Vac_im[:, b_ac_c[i]], E_im[:, tr_E], 1, 0, cc-1, cc, 0, cc)) + b_conv[i] * (conv1(Vac_im[:, b_ac_c[i]], E_re[:, tr_E], 1, cc-1, 0, cc) + conv2(M[:, i], Vac_im[:, b_ac_c[i]], E_re[:, tr_E], 1, 0, cc-1, cc, 0, cc)) - b_conv[i] * conv2(M[:, i], E_im[:, tr_E], Vac_re[:, b_ac_c[i]], 0, 0, cc-1, cc-1, 1, cc)

rhs9[i] = G0[i] * np.real(conv2(If[:, i], If[:, i], Vdc[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc)) + g_conv[i] * (conv1(M[:, i], Vdc_re[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_re[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) - b_conv[i] * (conv1(M[:, i], Vdc_im[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_im[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) - bc_shunt[i] / 2 * conv2(M[:, i], M[:, i], Vdc_im[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc) - g_conv[i] * conv1(M[:, i], Vac_re[:, b_ac_c[i]], 1, cc-1, 0, cc) + b_conv[i] * conv1(M[:, i], Vac_im[:, b_ac_c[i]], 1, cc-1, 0, cc)

rhs10[i] = G0[i] * np.imag(conv2(If[:, i], If[:, i], Vdc[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc)) + b_conv[i] * (conv1(M[:, i], Vdc_re[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_re[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) + g_conv[i] * (conv1(M[:, i], Vdc_im[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_im[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) + bc_shunt[i] / 2 * conv2(M[:, i], M[:, i], Vdc_re[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc) + g_conv[i] * (conv1(Vac_re[:, b_ac_c[i]], E_im[:, tr_E], 1, cc-1, 0, cc) + conv2(M[:, i], Vac_re[:, b_ac_c[i]], E_im[:, tr_E], 1, 0, cc-1, cc, 0, cc)) - b_conv[i] * (conv1(Vac_re[:, b_ac_c[i]], E_re[:, tr_E], 1, cc-1, 0, cc) + conv2(M[:, i], Vac_re[:, b_ac_c[i]], E_re[:, tr_E], 1, 0, cc-1, cc, 0, cc)) - b_conv[i] * (conv1(Vac_im[:, b_ac_c[i]], E_im[:, tr_E], 1, cc-1, 0, cc) + conv2(M[:, i], Vac_im[:, b_ac_c[i]], E_im[:, tr_E], 1, 0, cc-1, cc, 0, cc)) + np.real(1j * conv3(B[:, tr_B], M[:, i], M[:, i], Vdc[:, b_dc_c[i]], 0, 0, 0, cc-2, cc-1, cc-1, 1, cc)) - g_conv[i] * conv2(M[:, i], E_re[:, tr_E], Vac_im[:, b_ac_c[i]], 0, 0, cc-1, cc-1, 1, cc)

rhs10[i] = G0[i] * np.imag(conv2(If[:, i], If[:, i], Vdc[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc)) + b_conv[i] * (conv1(M[:, i], Vdc_re[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_re[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) + g_conv[i] * (conv1(M[:, i], Vdc_im[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_im[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) + bc_shunt[i] / 2 * conv2(M[:, i], M[:, i], Vdc_re[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc) - g_conv[i] * conv1(M[:, i], Vac_im[:, b_ac_c[i]], 0, cc-1, 1, cc) - b_conv[i] * conv1(M[:, i], Vac_re[:, b_ac_c[i]], 1, cc-1, 0, cc) + np.real(1j * conv3(B[:, tr_B], M[:, i], M[:, i], Vdc[:, b_dc_c[i]], 0, 0, 0, cc-2, cc-1, cc-1, 1, cc))

rhs10[i] = G0[i] * np.imag(conv2(If[:, i], If[:, i], Vdc[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc)) + b_conv[i] * (conv1(M[:, i], Vdc_re[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_re[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) + g_conv[i] * (conv1(M[:, i], Vdc_im[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_im[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) + bc_shunt[i] / 2 * conv2(M[:, i], M[:, i], Vdc_re[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc) + g_conv[i] * (conv1(Vac_re[:, b_ac_c[i]], E_im[:, tr_E], 1, cc-1, 0, cc) + conv2(M[:, i], Vac_re[:, b_ac_c[i]], E_im[:, tr_E], 1, 0, cc-1, cc, 0, cc)) - b_conv[i] * (conv1(Vac_re[:, b_ac_c[i]], E_re[:, tr_E], 1, cc-1, 0, cc) + conv2(M[:, i], Vac_re[:, b_ac_c[i]], E_re[:, tr_E], 1, 0, cc-1, cc, 0, cc)) - b_conv[i] * (conv1(Vac_im[:, b_ac_c[i]], E_im[:, tr_E], 1, cc-1, 0, cc) + conv2(M[:, i], Vac_im[:, b_ac_c[i]], E_im[:, tr_E], 1, 0, cc-1, cc, 0, cc)) - g_conv[i] * conv2(M[:, i], E_re[:, tr_E], Vac_im[:, b_ac_c[i]], 0, 0, cc-1, cc-1, 1, cc)

rhs10[i] = G0[i] * np.imag(conv2(If[:, i], If[:, i], Vdc[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc)) + b_conv[i] * (conv1(M[:, i], Vdc_re[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_re[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) + g_conv[i] * (conv1(M[:, i], Vdc_im[:, b_dc_c[i]], 1, cc-1, 0, cc) + conv2(M[:, i], M[:, i], Vdc_im[:, b_dc_c[i]], 1, 0, cc-1, cc, 0, cc)) + bc_shunt[i] / 2 * conv2(M[:, i], M[:, i], Vdc_re[:, b_dc_c[i]], 0, 0, cc-1, cc-1, 1, cc) - g_conv[i] * conv1(M[:, i], Vac_im[:, b_ac_c[i]], 0, cc-1, 1, cc) - b_conv[i] * conv1(M[:, i], Vac_re[:, b_ac_c[i]], 1, cc-1, 0, cc)