%STARTUP

%% add MATPOWER paths
addpath( ...
    'C:\Users\Josep\Desktop\Convertidor\FGBM\FGBM_Matpower\matpower-master\lib', ...
    'C:\Users\Josep\Desktop\Convertidor\FGBM\FGBM_Matpower\matpower-master\lib\t', ...
    'C:\Users\Josep\Desktop\Convertidor\FGBM\FGBM_Matpower\matpower-master\data', ...
    'C:\Users\Josep\Desktop\Convertidor\FGBM\FGBM_Matpower\matpower-master\mips\lib', ...
    'C:\Users\Josep\Desktop\Convertidor\FGBM\FGBM_Matpower\matpower-master\mips\lib\t', ...
    'C:\Users\Josep\Desktop\Convertidor\FGBM\FGBM_Matpower\matpower-master\most\lib', ...
    'C:\Users\Josep\Desktop\Convertidor\FGBM\FGBM_Matpower\matpower-master\most\lib\t', ...
    'C:\Users\Josep\Desktop\Convertidor\FGBM\FGBM_Matpower\matpower-master\mp-opt-model\lib', ...
    'C:\Users\Josep\Desktop\Convertidor\FGBM\FGBM_Matpower\matpower-master\mp-opt-model\lib\t', ...
    'C:\Users\Josep\Desktop\Convertidor\FGBM\FGBM_Matpower\matpower-master\mptest\lib', ...
    'C:\Users\Josep\Desktop\Convertidor\FGBM\FGBM_Matpower\matpower-master\mptest\lib\t', ...
    '-end' );
